# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20160428_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='Horizontal Grid Number')),
                ('y', models.IntegerField(verbose_name='Vertical Grid Number')),
                ('attempt', models.IntegerField(verbose_name='Situation of attempt')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Profile'),
        ),
    ]
