# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_profile_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='room',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
    ]
