# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ws_id',
            field=models.IntegerField(null=True),
        ),
    ]
